In [1]:
## TO RUN ON THE CLOUD 

## preprocessed the data before starting the slide
## import embeddings <s
import os

# Define the URI to point to your manual process
os.environ["FIFTYONE_DATABASE_URI"] = "mongodb://localhost:44123"

import fiftyone as fo

# Verify connection
print(fo.core.odm.database.get_db_conn())

You are running the oldest supported major version of MongoDB. Please refer to https://deprecation.voxel51.com for deprecation notices. You can suppress this exception by setting your `database_validation` config parameter to `False`. See https://docs.voxel51.com/user_guide/config.html#configuring-a-mongodb-connection for more information
Database(MongoClient(host=['localhost:44123'], document_class=dict, tz_aware=False, connect=True, appname='fiftyone'), 'fiftyone')

In [2]:
import numpy as np 
from fiftyone import ViewField

In [3]:
import sys
%load_ext autoreload
%autoreload 2

In [3]:
fo.list_datasets()

['FLPLAN',
 'UM_teste',
 'WPonly_1024ov224',
 'flplan200',
 'flplanpatches',
 'nc765',
 'nc765_T1024ov224',
 'nc765_T2048ov224',
 'tiles2048_merged',
 'tiles_merged',
 'tiles_merged_2048',
 'train_nc_wp_T1024ov224',
 'umflplan_T1024ov224',
 'umflplan_T2048ov224',
 'wp125',
 'wp125_T1024ov224',
 'wp125_T2048ov224']

In [9]:
dataset = fo.load_dataset('UM_teste')

In [10]:
positive = dataset.match(
    ViewField("type_label").contains_str("positive")
)

In [8]:
positive_wp = dataset.match(
    ViewField("type_label").contains_str("positive")
)

In [ ]:
new_ds = fo.Dataset("wp_final_test", persistent=True)
new_ds.add_collection(
    positive
)
new_ds.add_collection(
    positive_wp
)

In [12]:
new_ds

Name:        wp_final_test
Media type:  image
Num samples: 476
Persistent:  True
Tags:        []
Sample fields:
    id:               fiftyone.core.fields.ObjectIdField
    filepath:         fiftyone.core.fields.StringField
    tags:             fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:         fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    created_at:       fiftyone.core.fields.DateTimeField
    last_modified_at: fiftyone.core.fields.DateTimeField
    type_label:       fiftyone.core.fields.StringField
    ground_truth:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    region:           fiftyone.core.fields.StringField
    mission_name:     fiftyone.core.fields.StringField
    parent_name:      fiftyone.core.fields.StringField
    gt_field:         fiftyone.core.fields.StringField
    min_area_ratio:   fiftyone.core.fields.FloatField
    n_boxes_in_tile:  fiftyone.core.fields.IntField
    n_boxes_written:  fiftyone.core.fields.IntField
    source_image:     fiftyone.core.fields.StringField
    tile_name:        fiftyone.core.fields.StringField
    x_start:          fiftyone.core.fields.IntField
    y_start:          fiftyone.core.fields.IntField
    dataset_sr:       fiftyone.core.fields.StringField

In [13]:
new_ds.count_values("tags")

{'val_0': 42, 'train_0': 379, 'test_0': 55}

In [17]:
new_ds.untag_samples("train_0")

In [24]:
session = fo.launch_app(new_ds,auto=False, port=5151)

Could not connect session, trying again in 10 seconds

Session launched. Run `session.show()` to open the App in a cell output.

# Composing the test set for Object Detection

In [8]:
positive = dataset.match(
    ViewField("type_label").contains_str("positive")
)
session.view = positive

In [19]:
new_ds.match_tags("test_0").count_values("parent_name")

{'FPLAN_M4_UM_M46_F1_2025_P_3-699848dc6accc_26_03_10': 11,
 'FPLAN_P4P_UM_M33_F1_2025_GSP-697b1d86c5e8c_26_03_09': 15,
 'FPLAN_M4_UM_M46_F1_2025_P_4-699849b7e7a3f_26_03_10': 8,
 'FPLAN_M4_UM_M13_F1_2025_P_2-6973e462cbf54_26_03_09': 2,
 'FPLAN_P4_UM_M35_F1_2025_GSP-69970e580c6f4_26_03_10': 13,
 'UM_M3': 6}

In [18]:
new_ds.count_values("parent_name")

{'FRIWEN_M11': 49,
 'FPLAN_M4_UM_M40_F1_2025_P_4-69983ff2b2579_26_03_10': 3,
 'FPLAN_P4_UM_M35_F1_2025_GSP-69970e580c6f4_26_03_10': 13,
 'FPLAN_P4P_UM_M48_F1_2025_GSP-697e1055e6795_26_03_09': 16,
 'FPLAN_M4_UM_M40_F1_2025_P_2-699839d1afc67_26_03_10': 8,
 'FRIWEN_M19': 3,
 'FRIWEN_M8': 54,
 'FPLAN_M4_UM_M4_F1_2025_P-69723dd2b68b6_26_03_09': 3,
 'UM_M1': 26,
 'FPLAN_M4_UM_M13_F1_2025_P_1-6973989e86e75_26_03_09': 2,
 'FPLAN_M4_UM_M40_F1_2025_P_1-69983452bef98_26_03_10': 1,
 'UM_M5': 67,
 'UM_M6': 18,
 'MANTASANDY_M5': 4,
 'FRIWEN_M53': 10,
 'FPLAN_M4_UM_M46_F1_2025_P_4-699849b7e7a3f_26_03_10': 8,
 'GAM_M10': 8,
 'FPLAN_M4_UM_M40_F1_2025_P_3-69983e8785b05_26_03_10': 22,
 'GAM_M2': 23,
 'FPLAN_M4_UM_M46_F1_2025_P_3-699848dc6accc_26_03_10': 11,
 'FPLAN_P4P_UM_M33_F1_2025_GSP-697b1d86c5e8c_26_03_09': 15,
 'FRIWEN_M12': 23,
 'UM_M3': 6,
 'FPLAN_M4_UM_M46_F1_2025_P_2-699847233596f_26_03_10': 8,
 'GAM_M1': 28,
 'FPLAN_M4_UM_M13_F1_2025_P_3-6973996330251_26_03_09': 2,
 'FPLAN_M4_UM_M13_F1_2025_P_2-6973e462cbf54_26_03_09': 2,
 'FPLAN_P4P_UM_M15_F1_2025_GSP-697622d8e60f0_26_03_09': 16,
 'FPLAN_M4_UM_M13_F1_2025_P_4-6973e124ed55b_26_03_09': 11,
 'UM_M2': 16}

In [27]:
val_val = new_ds.match(
    ViewField("parent_name").contains_str(
        ["GAM_M10","FRIWEN_M19",
         "FPLAN_M4_UM_M40_F1_2025_P_4-69983ff2b2579_26_03_10","FPLAN_M4_UM_M13_F1_2025_P_3-6973996330251_26_03_09"]
    )
)
val_val

Dataset:     wp_final_test
Media type:  image
Num samples: 16
Sample fields:
    id:               fiftyone.core.fields.ObjectIdField
    filepath:         fiftyone.core.fields.StringField
    tags:             fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:         fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    created_at:       fiftyone.core.fields.DateTimeField
    last_modified_at: fiftyone.core.fields.DateTimeField
    type_label:       fiftyone.core.fields.StringField
    ground_truth:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    region:           fiftyone.core.fields.StringField
    mission_name:     fiftyone.core.fields.StringField
    parent_name:      fiftyone.core.fields.StringField
    gt_field:         fiftyone.core.fields.StringField
    min_area_ratio:   fiftyone.core.fields.FloatField
    n_boxes_in_tile:  fiftyone.core.fields.IntField
    n_boxes_written:  fiftyone.core.fields.IntField
    source_image:     fiftyone.core.fields.StringField
    tile_name:        fiftyone.core.fields.StringField
    x_start:          fiftyone.core.fields.IntField
    y_start:          fiftyone.core.fields.IntField
    dataset_sr:       fiftyone.core.fields.StringField
View stages:
    1. Match(filter={'$expr': {'$regexMatch': {...}}})

In [29]:
val_val.tag_samples("val_0")

In [32]:
session.view = new_ds.match_tags(["test_0","val_0"],bool=False)

In [28]:
session.view = val_val

In [20]:
test_test = positive.match(
    ViewField("parent_name").contains_str(
        ["FPLAN_M4_UM_M46_F1_2025_P_3-699848dc6accc_26_03_10","FPLAN_M4_UM_M46_F1_2025_P_4-699849b7e7a3f_26_03_10",
         "FPLAN_M4_UM_M13_F1_2025_P_2-6973e462cbf54_26_03_09","UM_M3"]
    )
)
session.view = test_test

In [33]:
session.freeze

<bound method Session.freeze of Dataset:          wp_final_test
Media type:       image
Num samples:      405
Selected samples: 8
Selected labels:  0
Session URL:      http://localhost:5151/
View stages:
    1. MatchTags(tags=['test_0', 'val_0'], bool=False, all=False)>

In [37]:
session.selected

['6a33d1a619d8f6f6ef56935c',
 '6a33d1a619d8f6f6ef569342',
 '6a33d1a619d8f6f6ef56933b',
 '6a33d1a619d8f6f6ef56933c']

In [38]:
new_ds['6a33d1a619d8f6f6ef56935c',
 '6a33d1a619d8f6f6ef569342',
 '6a33d1a619d8f6f6ef56933b',
 '6a33d1a619d8f6f6ef56933c'].tag_samples('test_0')

In [41]:
new_ds.match_tags(["test_0","val_0"],bool=False).tag_samples("train_0")

In [42]:
new_ds.count_values("tags")

{'test_0': 59, 'train_0': 393, 'val_0': 24}

In [27]:
train_train = positive.match(
    ~ViewField("parent_name").contains_str(["FPLAN_M4_UM_M46_F1_2025_P_3-699848dc6accc_26_03_10","FPLAN_M4_UM_M46_F1_2025_P_4-699849b7e7a3f_26_03_10",
         "FPLAN_M4_UM_M13_F1_2025_P_2-6973e462cbf54_26_03_09","UM_M3"]
))

train_train.tag_samples("train_0")

In [24]:
dataset.count_values("tags")

{'test_0': 55}

In [28]:
dataset.save_view("train_view",train_train)
dataset.save_view("test_view",test_test)

## Active Learning

In [ ]:
## taking the embeddings of the train set

# Classification

In [37]:
# load embeddings 
from sklearn.preprocessing import normalize

data_embedding_tile        = np.load("/share/home/e2406743/code/Dugongs_IRISA-MARBEC-LIRMM/chapter3/embeddings_dinov3/merged_1024o224_fullimage_embeddings.npz")

sample_ids = data_embedding_tile['sample_ids']

embedding_retrieved = data_embedding_tile['embeddings']

In [38]:
dataset

Name:        tiles_merged
Media type:  image
Num samples: 11123
Persistent:  True
Tags:        []
Sample fields:
    id:               fiftyone.core.fields.ObjectIdField
    filepath:         fiftyone.core.fields.StringField
    tags:             fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:         fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    created_at:       fiftyone.core.fields.DateTimeField
    last_modified_at: fiftyone.core.fields.DateTimeField
    type_label:       fiftyone.core.fields.StringField
    ground_truth:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    region:           fiftyone.core.fields.StringField
    mission_name:     fiftyone.core.fields.StringField
    parent_name:      fiftyone.core.fields.StringField
    gt_field:         fiftyone.core.fields.StringField
    min_area_ratio:   fiftyone.core.fields.FloatField
    n_boxes_in_tile:  fiftyone.core.fields.IntField
    n_boxes_written:  fiftyone.core.fields.IntField
    source_image:     fiftyone.core.fields.StringField
    tile_name:        fiftyone.core.fields.StringField
    x_start:          fiftyone.core.fields.IntField
    y_start:          fiftyone.core.fields.IntField
    dataset_sr:       fiftyone.core.fields.StringField
    umap:             fiftyone.core.fields.ListField(fiftyone.core.fields.FloatField)
    cluster_label:    fiftyone.core.fields.FloatField
    uniqueness_score: fiftyone.core.fields.FloatField
    count_pos_sr:     fiftyone.core.fields.StringField
    subregion:        fiftyone.core.fields.StringField
    source_stem:      fiftyone.core.fields.StringField

In [39]:
label_lookup = {
        s.id: s.get_field("type_label")
        for s in dataset.select_fields("type_label")
    }

In [13]:
dataset.count_values("dataset_sr")

{'UM_flplan': 636, 'WPmix': 904}

In [9]:
dataset

Name:        tiles_merged
Media type:  image
Num samples: 11123
Persistent:  True
Tags:        []
Sample fields:
    id:               fiftyone.core.fields.ObjectIdField
    filepath:         fiftyone.core.fields.StringField
    tags:             fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata:         fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)
    created_at:       fiftyone.core.fields.DateTimeField
    last_modified_at: fiftyone.core.fields.DateTimeField
    type_label:       fiftyone.core.fields.StringField
    ground_truth:     fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.labels.Detections)
    region:           fiftyone.core.fields.StringField
    mission_name:     fiftyone.core.fields.StringField
    parent_name:      fiftyone.core.fields.StringField
    gt_field:         fiftyone.core.fields.StringField
    min_area_ratio:   fiftyone.core.fields.FloatField
    n_boxes_in_tile:  fiftyone.core.fields.IntField
    n_boxes_written:  fiftyone.core.fields.IntField
    source_image:     fiftyone.core.fields.StringField
    tile_name:        fiftyone.core.fields.StringField
    x_start:          fiftyone.core.fields.IntField
    y_start:          fiftyone.core.fields.IntField
    dataset_sr:       fiftyone.core.fields.StringField
    umap:             fiftyone.core.fields.ListField(fiftyone.core.fields.FloatField)
    cluster_label:    fiftyone.core.fields.FloatField
    uniqueness_score: fiftyone.core.fields.FloatField

In [14]:
dataset.count_values("mission_name")

{'FRIWEN': 370, 'GAM': 162, 'MANTASANDY': 18, 'UM': 990}

In [64]:
# WITHOUT -UM  - train and test set 
# wp_mix = dataset.match(
#     (ViewField("dataset_sr").contains_str("WPmix"))
#     & (ViewField("mission_name").is_in(("MANTASANDY", "FRIWEN", "GAM")))
# )

# WITH UM
wp_mix = dataset.match(
    (ViewField("dataset_sr").contains_str("WPmix")))

nc_view = dataset.match(ViewField("dataset_sr").contains_str("NC_flplan"))

train_set_view = wp_mix.concat(nc_view)
train_set_id   = train_set_view.values('id')

um_test_ids = dataset.match(ViewField("dataset_sr").contains_str("UM_flplan")).values('id')

In [40]:
# this is a similar analysis but for the 2048 input dimension tiles
## 2048x2048

wp125 = dataset.match(
    (ViewField("dataset_sr").contains_str("WPmix"))
   ## & (ViewField("mission_name").is_in(("MANTASANDY", "FRIWEN", "GAM")))
)

#train_set_view = wp_mix.concat(nc_view)
train_set_id   = wp125.values('id')

um_test_ids = dataset.match(ViewField("dataset_sr").contains_str("UM_flplan")).values('id')

In [62]:
train_set_view.count_values('dataset_sr')

{'NC_flplan': 5728, 'WPmix': 2640}

In [65]:
train_set_view.count_values('mission_name')

{'Flight_197': 400,
 'Flight_235': 32,
 'Flight_196': 504,
 'Flight_234': 16,
 'Flight_215': 296,
 'Flight_232': 184,
 'Flight_213': 328,
 'Flight_205': 72,
 'Flight_198': 584,
 'Flight_231': 96,
 'Flight_207': 1024,
 'Flight_214': 152,
 'Flight_225': 16,
 'Flight_226': 40,
 'GAM': 405,
 'MANTASANDY': 105,
 'Flight_209': 664,
 'Flight_220': 160,
 'UM': 1185,
 'Flight_222': 136,
 'Flight_219': 184,
 'Flight_212': 288,
 'FRIWEN': 945,
 'Flight_200': 80,
 'Flight_218': 176,
 'Flight_199': 64,
 'Flight_233': 48,
 'Flight_211': 136,
 'Flight_195': 48}

In [41]:
#Lookup table id -> positive/negative 
label_lookup = {
    s.id: s.get_field("type_label")
    for s in dataset.select_fields("type_label")
}

In [42]:
# map in order to not mixed embedding and index
#  each sample_id maps a row index in the embedding array 
sample_id_to_row = {sid: i for i, sid in enumerate(sample_ids)}

def _build_X_y(ids):
    """
    Builds X and y from the SAME id list, in the SAME order, in one pass.
    This guarantees row i of X and row i of y always refer to the same
    sample.
    """
    rows, labels, missing_embedding, missing_label = [], [], [], []

    for sid in ids:
        row_idx = sample_id_to_row.get(sid)
        if row_idx is None:
            missing_embedding.append(sid)
            continue

        lab = label_lookup.get(sid)
        if lab == "positive":
            y_val = 1
        elif lab == "negative":
            y_val = 0
        else:
            missing_label.append(sid)
            continue

        rows.append(row_idx)
        labels.append(y_val)

    X = embedding_retrieved[rows]
    y = np.array(labels)
    kept_ids = np.array([ids[i] for i in range(len(ids))
                         if ids[i] not in missing_embedding and ids[i] not in missing_label])
    return X, y, kept_ids, missing_embedding, missing_label


X_train, y_train, train_ids_kept, miss_emb_tr, miss_lab_tr = _build_X_y(train_set_id)
X_test,  y_test,  test_ids_kept,  miss_emb_te, miss_lab_te = _build_X_y(um_test_ids)

print(f"Train: {X_train.shape[0]} rows  (missing_embedding={len(miss_emb_tr)}, "
      f"missing_label={len(miss_lab_tr)})")
print(f"Test:  {X_test.shape[0]} rows  (missing_embedding={len(miss_emb_te)}, "
      f"missing_label={len(miss_lab_te)})")

X_train = normalize(X_train, norm="l2")
X_test  = normalize(X_test,  norm="l2")

Train: 2640 rows  (missing_embedding=0, missing_label=0)
Test:  2755 rows  (missing_embedding=0, missing_label=0)

In [43]:
X_train.shape

(2640, 1024)

In [44]:
X_test.shape

(2755, 1024)

In [21]:
y_train.shape

(904,)

In [22]:
y_test.shape

(636,)

In [45]:
from src.classification import fit_logistic_regression, evaluate_predictions, fit_random_forest

In [46]:
result_lr  = fit_logistic_regression(
    X_train, y_train, X_test, y_test, test_ids=um_test_ids
)

=== Logistic Regression ===
  Accuracy : 0.9855
  Precision: 0.8301
  Recall   : 0.9007
  F1       : 0.8639
  ROC-AUC  : 0.9865
  Confusion matrix [[TN,FP],[FN,TP]]:
[[2588   26]
 [  14  127]]
              precision    recall  f1-score   support

    negative       0.99      0.99      0.99      2614
    positive       0.83      0.90      0.86       141

    accuracy                           0.99      2755
   macro avg       0.91      0.95      0.93      2755
weighted avg       0.99      0.99      0.99      2755

  Failed predictions: 40 / 2755

In [25]:
result_lr.keys()

dict_keys(['model', 'y_pred', 'y_proba', 'metrics', 'results_df', 'failed_ids'])

In [27]:
result_lr['results_df']

,sample_id,y_true,y_pred,correct,model,y_proba
0,6a44dfc4ac26e9d0f92e8ef7,1,0,False,Logistic Regression,0.474830
1,6a44dfc4ac26e9d0f92e8ef8,1,0,False,Logistic Regression,0.331456
2,6a44dfc4ac26e9d0f92e8ef9,1,0,False,Logistic Regression,0.445026
3,6a44dfc4ac26e9d0f92e8efa,1,0,False,Logistic Regression,0.482168
4,6a44dfc4ac26e9d0f92e8efb,1,1,True,Logistic Regression,0.679752
...,...,...,...,...,...,...
631,6a44dfc4ac26e9d0f92e916e,0,0,True,Logistic Regression,0.391313
632,6a44dfc4ac26e9d0f92e916f,0,0,True,Logistic Regression,0.474862
633,6a44dfc4ac26e9d0f92e9170,0,0,True,Logistic Regression,0.467781
634,6a44dfc4ac26e9d0f92e9171,0,0,True,Logistic Regression,0.361752
635,6a44dfc4ac26e9d0f92e9172,0,0,True,Logistic Regression,0.398803

In [16]:
%reload_ext
from src import classification

UsageError: Missing module name.

In [17]:
from src.classification import fit_logistic_regression, fit_random_forest, fit_mlp

In [47]:
from src.classification import fit_logistic_regression, fit_random_forest

#result_lr = fit_logistic_regression(X_train, y_train, X_test, y_test, test_ids=um_test_ids)
result_rf = fit_random_forest(X_train, y_train, X_test, y_test, test_ids=um_test_ids)

=== Random Forest ===
  Accuracy : 0.9844
  Precision: 0.9804
  Recall   : 0.7092
  F1       : 0.8230
  ROC-AUC  : 0.9826
  Confusion matrix [[TN,FP],[FN,TP]]:
[[2612    2]
 [  41  100]]
              precision    recall  f1-score   support

    negative       0.98      1.00      0.99      2614
    positive       0.98      0.71      0.82       141

    accuracy                           0.98      2755
   macro avg       0.98      0.85      0.91      2755
weighted avg       0.98      0.98      0.98      2755

  Failed predictions: 43 / 2755

In [50]:
result_rf['results_df'].loc[(result_rf['results_df']["y_true"])==1&(result_rf['results_df']["y_pred"]==0)]

,sample_id,y_true,y_pred,correct,model,y_proba
0,6a33d1a619d8f6f6ef5692ea,1,0,False,Random Forest,0.130000
1,6a33d1a619d8f6f6ef5692eb,1,0,False,Random Forest,0.030000
6,6a33d1a619d8f6f6ef5692f0,1,0,False,Random Forest,0.416667
9,6a33d1a619d8f6f6ef5692f3,1,0,False,Random Forest,0.233333
10,6a33d1a619d8f6f6ef5692f4,1,0,False,Random Forest,0.313333
14,6a33d1a619d8f6f6ef5692f8,1,0,False,Random Forest,0.166667
15,6a33d1a619d8f6f6ef5692f9,1,0,False,Random Forest,0.416667
16,6a33d1a619d8f6f6ef5692fa,1,0,False,Random Forest,0.466667
17,6a33d1a619d8f6f6ef5692fb,1,0,False,Random Forest,0.236667
23,6a33d1a619d8f6f6ef569301,1,0,False,Random Forest,0.246667
31,6a33d1a619d8f6f6ef569309,1,0,False,Random Forest,0.413333
32,6a33d1a619d8f6f6ef56930a,1,0,False,Random Forest,0.240000
33,6a33d1a619d8f6f6ef56930b,1,0,False,Random Forest,0.366667
34,6a33d1a619d8f6f6ef56930c,1,0,False,Random Forest,0.436667
36,6a33d1a619d8f6f6ef56930e,1,0,False,Random Forest,0.066667
37,6a33d1a619d8f6f6ef56930f,1,0,False,Random Forest,0.056667
38,6a33d1a619d8f6f6ef569310,1,0,False,Random Forest,0.456667
42,6a33d1a619d8f6f6ef569314,1,0,False,Random Forest,0.313333
48,6a33d1a619d8f6f6ef56931a,1,0,False,Random Forest,0.340000
53,6a33d1a619d8f6f6ef56931f,1,0,False,Random Forest,0.103333
54,6a33d1a619d8f6f6ef569320,1,0,False,Random Forest,0.146667
56,6a33d1a619d8f6f6ef569322,1,0,False,Random Forest,0.326667
57,6a33d1a619d8f6f6ef569323,1,0,False,Random Forest,0.206667
58,6a33d1a619d8f6f6ef569324,1,0,False,Random Forest,0.126667
60,6a33d1a619d8f6f6ef569326,1,0,False,Random Forest,0.300000
78,6a33d1a619d8f6f6ef569338,1,0,False,Random Forest,0.226667
79,6a33d1a619d8f6f6ef569339,1,0,False,Random Forest,0.176667
83,6a33d1a619d8f6f6ef56933d,1,0,False,Random Forest,0.463333
84,6a33d1a619d8f6f6ef56933e,1,0,False,Random Forest,0.110000
106,6a33d1a619d8f6f6ef569354,1,0,False,Random Forest,0.250000
109,6a33d1a619d8f6f6ef569357,1,0,False,Random Forest,0.160000
110,6a33d1a619d8f6f6ef569358,1,0,False,Random Forest,0.010000
116,6a33d1a619d8f6f6ef56935e,1,0,False,Random Forest,0.136667
127,6a33d1a619d8f6f6ef569369,1,0,False,Random Forest,0.430000
130,6a33d1a619d8f6f6ef56936c,1,0,False,Random Forest,0.046667
133,6a33d1a619d8f6f6ef56936f,1,0,False,Random Forest,0.470000
134,6a33d1a619d8f6f6ef569370,1,0,False,Random Forest,0.306667
135,6a33d1a619d8f6f6ef569371,1,0,False,Random Forest,0.403333
136,6a33d1a619d8f6f6ef569372,1,0,False,Random Forest,0.300000
137,6a33d1a619d8f6f6ef569373,1,0,False,Random Forest,0.136667
138,6a33d1a619d8f6f6ef569374,1,0,False,Random Forest,0.056667
1545,6a33d1a719d8f6f6ef5698f3,0,1,False,Random Forest,0.786667
1752,6a33d1a719d8f6f6ef5699c2,0,1,False,Random Forest,0.550000

In [30]:
failed_df = result_rf['results_df'].loc[(result_rf['results_df']["y_true"])==1&(result_rf['results_df']["y_pred"]==0)]
failed_df.loc[failed_df['y_true']==1]
list_fn = failed_df.loc[failed_df['y_true']==1]['sample_id'].to_list()
len(list_fn)

66

In [76]:
session = fo.launch_app(dataset,auto=False,port=5151)

Session launched. Run `session.show()` to open the App in a cell output.

In [77]:
view = dataset.select(list_fn)
session.view = view

In [55]:
%reload_ext src

In [48]:
from src.classification import fit_mlp, DugongMLP


# Or swap in a different architecture entirely
result_mlp2 = fit_mlp(
    X_train, y_train, X_test, y_test, test_ids=um_test_ids,
    model_fn=lambda: DugongMLP(input_dim=X_train.shape[1]),  
)

  Train: 2244 (pos=285)  Val: 396 (pos=50)  device=cuda
  pos_weight (n_neg/n_pos) = 6.874
  Model: DugongMLP
  epoch   1  train_loss=0.8399  val_loss=0.4134  best=0.4134  no_improve=0
  epoch  10  train_loss=0.2174  val_loss=0.2662  best=0.2309  no_improve=1
  epoch  20  train_loss=0.2125  val_loss=0.2845  best=0.2257  no_improve=7
  epoch  30  train_loss=0.1961  val_loss=0.2694  best=0.1892  no_improve=3
  epoch  40  train_loss=0.1528  val_loss=0.3598  best=0.1892  no_improve=13
  Early stopping at epoch 42 (no val improvement for 15 epochs).
  Restored weights from best val_loss=0.1892
  Tuned threshold (max f1 on val) = 0.715  (val f1=0.9091)

=== MLP ===
  Accuracy : 0.9848
  Precision: 0.8414
  Recall   : 0.8652
  F1       : 0.8531
  ROC-AUC  : 0.9791
  Confusion matrix [[TN,FP],[FN,TP]]:
[[2591   23]
 [  19  122]]
              precision    recall  f1-score   support

    negative       0.99      0.99      0.99      2614
    positive       0.84      0.87      0.85       141

    accuracy                           0.98      2755
   macro avg       0.92      0.93      0.92      2755
weighted avg       0.98      0.98      0.98      2755

  Failed predictions: 42 / 2755

In [33]:
import torch
import torch.nn as nn
from src.classification import fit_mlp, DugongMLP

In [34]:

# smaller mlp
class WiderMLP(nn.Module):
    def __init__(self, input_dim=1024):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 128), nn.ReLU(),
            nn.Linear(128, 1),
        )
    def forward(self, x):
        return self.net(x).squeeze(-1)

result_mlp3 = fit_mlp(
    X_train, y_train, X_test, y_test, test_ids=um_test_ids,
    model_fn=lambda: WiderMLP(input_dim=X_train.shape[1]),
    val_size = 0.10,
    batch_size = 32,
    max_epochs = 100,
    patience = 25,
    lr = 1e-3,
)

  Train: 813 (pos=422)  Val: 91 (pos=47)  device=cuda
  pos_weight (n_neg/n_pos) = 0.927
  Model: WiderMLP
  epoch   1  train_loss=0.6336  val_loss=0.5842  best=0.5842  no_improve=0

  epoch  10  train_loss=0.3013  val_loss=0.3216  best=0.3177  no_improve=1
  epoch  20  train_loss=0.2309  val_loss=0.2686  best=0.2649  no_improve=1
  epoch  30  train_loss=0.2069  val_loss=0.2405  best=0.2405  no_improve=0
  epoch  40  train_loss=0.1805  val_loss=0.2254  best=0.2254  no_improve=0
  epoch  50  train_loss=0.1601  val_loss=0.2260  best=0.2116  no_improve=5
  epoch  60  train_loss=0.1540  val_loss=0.2552  best=0.1997  no_improve=1
  epoch  70  train_loss=0.1422  val_loss=0.2239  best=0.1919  no_improve=3
  epoch  80  train_loss=0.1477  val_loss=0.1925  best=0.1869  no_improve=2
  epoch  90  train_loss=0.1348  val_loss=0.1881  best=0.1836  no_improve=6
  epoch 100  train_loss=0.1198  val_loss=0.1753  best=0.1753  no_improve=0
  Restored weights from best val_loss=0.1753
  Tuned threshold (max f1 on val) = 0.265  (val f1=0.9592)

=== MLP ===
  Accuracy : 0.8491
  Precision: 0.6296
  Recall   : 0.6489
  F1       : 0.6391
  ROC-AUC  : 0.8772
  Confusion matrix [[TN,FP],[FN,TP]]:
[[455  50]
 [ 46  85]]
              precision    recall  f1-score   support

    negative       0.91      0.90      0.90       505
    positive       0.63      0.65      0.64       131

    accuracy                           0.85       636
   macro avg       0.77      0.77      0.77       636
weighted avg       0.85      0.85      0.85       636

  Failed predictions: 96 / 636

In [49]:
## save df 
import pandas as pd 
final_df = pd.concat([
    result_mlp2['results_df'],
    result_rf['results_df'],
    result_lr['results_df']
])

final_df['DOMAIN_SHIFT'] = "NCandWPmixALL"
out_folder = "/share/home/e2406743/code/Dugongs_IRISA-MARBEC-LIRMM/chapter3/results_classification"
out_nme = "in1024_wptrained_UMtest.parquet"
final_df.to_parquet(os.path.join(out_folder,out_nme))

In [82]:
final_df

,sample_id,y_true,y_pred,correct,model,y_proba,DOMAIN_SHIFT
0,6a33d1a619d8f6f6ef5692ea,1,0,False,MLP,0.003480,NCandWPmixALL
1,6a33d1a619d8f6f6ef5692eb,1,0,False,MLP,0.002633,NCandWPmixALL
2,6a33d1a619d8f6f6ef5692ec,1,1,True,MLP,0.909066,NCandWPmixALL
3,6a33d1a619d8f6f6ef5692ed,1,1,True,MLP,0.992924,NCandWPmixALL
4,6a33d1a619d8f6f6ef5692ee,1,1,True,MLP,0.999224,NCandWPmixALL
...,...,...,...,...,...,...,...
2750,6a33d1a719d8f6f6ef569da8,0,0,True,Logistic Regression,0.195740,NCandWPmixALL
2751,6a33d1a719d8f6f6ef569da9,0,0,True,Logistic Regression,0.118306,NCandWPmixALL
2752,6a33d1a719d8f6f6ef569daa,0,0,True,Logistic Regression,0.142134,NCandWPmixALL
2753,6a33d1a719d8f6f6ef569dab,0,0,True,Logistic Regression,0.137941,NCandWPmixALL
2754,6a33d1a719d8f6f6ef569dac,0,0,True,Logistic Regression,0.250689,NCandWPmixALL

# Create a GIF

In [45]:
%reload_ext src

In [49]:
from src.gif_plot import create_failure_reveal_gif

info = create_failure_reveal_gif(
    filepaths= filepath_fn_rf,   # your list of image paths where the model missed
    output_path="NCtrained_RF_dugong_failures.gif",
    raw_duration_s=2,
    reveal_duration_s=1,
)

GIF saved -> NCtrained_RF_dugong_failures.gif
  Tiles: 20  Frames: 40 (2 per tile)
  Size: 19095.9 KB
  Requested durations (ms), first 4 frames: [2000, 1000, 2000, 1000]
  Actual durations read back from file, first 4 frames: [2000, 1000, 2000, 1000]